### ISSUE TITLE
Replace signature code with BotoAWSRequestsAuth?

### ISSUE THREAD

**Issue by russau** [argais/cloudtrail_aws_es#3]
https://github.com/argais/cloudtrail_aws_es/blob/860cee1c731be46a479cc47d02bdde772e77ff07/s3_lambda_es.py#L144

You might be interested in this feature of botocore: https://github.com/DavidMuller/aws-requests-auth#using-boto-to-automatically-gather-aws-credentials

The code would change to something like this, and you wouldn't need any of the signature code.  `BotoAWSRequestsAuth` will automatically pick up AWS credentials from the many locations boto supports -> http://boto3.readthedocs.io/en/latest/guide/configuration.html#configuring-credentials

``` python
auth = BotoAWSRequestsAuth(aws_host=es_host,
                           aws_region=region,
                           aws_service='es')
# sends the json to elasticsearch
req = requests.post(url, data=data, auth=auth)
print "status code: ", req.status_code
print "text", req.text
```

Let me know if you are interested - I could submit a pull request for this.

Thanks,
Russ

**Comment by argais** [comment]
Hi Russau. I haven't touched this code for a while now, so if you submit a PR I'll gladly merge it, or if you're actively using it and want to fork and take over I could just point to your repo too ;)
